// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeShopManagement.Models.Models;

public partial class Contact
{
    public Guid Id { get; set; }

    public Guid CustomerId { get; set; }

    public Guid AdminId { get; set; }

    public DateTime SendDate { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public Guid ProblemId { get; set; }

    public int Status { get; set; }

    public string Response { get; set; }

    public virtual User Admin { get; set; }

    public virtual User Customer { get; set; }

    public virtual ProblemType Problem { get; set; }
}