// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeShopManagement.Models.Models;

public partial class OrderDetail
{
    public Guid Id { get; set; }

    public Guid OrderId { get; set; }

    public int Quantity { get; set; }

    public Guid ProductId { get; set; }

    public decimal OrderPrice { get; set; }

    public int? Rating { get; set; }
    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}