// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeShopManagement.Models.Models;

public partial class Otp
{
    public Guid Id { get; set; }

    public string Email { get; set; }

    public string Otp1 { get; set; }

    public DateTime? ExpirationTime { get; set; }

    public int? Status { get; set; }
}