// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeShopManagement.Models.Models;

public partial class ProblemType
{
    public Guid Id { get; set; }

    public string ProblemName { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();
}