// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoffeeShopManagement.Models.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public int Role { get; set; }

    public string PhoneNumber { get; set; }

    public string Avatar { get; set; }

    public string Address { get; set; }

    public int Status { get; set; }

    public virtual ICollection<Contact> ContactAdmins { get; set; } = new List<Contact>();

    public virtual ICollection<Contact> ContactCustomers { get; set; } = new List<Contact>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}